// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuulj_tu5n9sT_RLJ7NujChES2QxtJUXo',
    appId: '1:956080447852:web:0417aa1e2a807b3b8f9349',
    messagingSenderId: '956080447852',
    projectId: 'panna-official',
    authDomain: 'panna-official.firebaseapp.com',
    storageBucket: 'panna-official.firebasestorage.app',
    measurementId: 'G-QQMS3CKCXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlDFQERKRxkYzGKAg1L4UEzGlGOoE4vFQ',
    appId: '1:956080447852:android:9fb7de8f5183c9a88f9349',
    messagingSenderId: '956080447852',
    projectId: 'panna-official',
    storageBucket: 'panna-official.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe-_sThadeD_ZG7XfsHxM8QBo1mtyybco',
    appId: '1:956080447852:ios:787b3b2ed951d1c28f9349',
    messagingSenderId: '956080447852',
    projectId: 'panna-official',
    storageBucket: 'panna-official.firebasestorage.app',
    iosBundleId: 'uk.app.panna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe-_sThadeD_ZG7XfsHxM8QBo1mtyybco',
    appId: '1:956080447852:ios:b029d355f85902768f9349',
    messagingSenderId: '956080447852',
    projectId: 'panna-official',
    storageBucket: 'panna-official.firebasestorage.app',
    iosBundleId: 'com.example.pannaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuulj_tu5n9sT_RLJ7NujChES2QxtJUXo',
    appId: '1:956080447852:web:4ac22456cb20a1208f9349',
    messagingSenderId: '956080447852',
    projectId: 'panna-official',
    authDomain: 'panna-official.firebaseapp.com',
    storageBucket: 'panna-official.firebasestorage.app',
    measurementId: 'G-T015RK2396',
  );

}